### ISSUE TITLE
Media queries

### ISSUE THREAD

**Issue by Xe** [AccentDesign/gcss#4]
I've been trying to port [Xess](https://github.com/Xe/Xess) to gcss as an exercise to see what I think about it and I've run into an issue, I can't properly express media queries like this:

```css
@media only screen and (max-device-width: 736px) {
  main {
    padding: 0;
  }
}
```

What's the gcss way to do this?
